name: Update JSON daily

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  update-json:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: pip install feedparser

      - name: Run script
        run: python Python/fetch_news.py

      - name: Commit JSON
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add JSON/data.json
          git commit -m "Update JSON" || echo "No changes"
          git push || echo "Push skipped"
