name: Update JSON

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - run: pip install feedparser

      - run: python script.py

      - run: |
          git config --global user.name "bot"
          git config --global user.email "bot@github.com"
          git add JSON/data.json
          git commit -m "Update JSON" || echo "No changes"
          git push
